.NET Monitor release
dotnet/dotnet-docker pull request #2853
Opened 2021-06-02 13:50 UTC by mthalman

Related to https://github.com/dotnet/dotnet-docker/issues/2852

2021-06-02 14:09 UTC, MichaelSimons approved these changes

2021-06-02 14:09 UTC, MichaelSimons commented on src/monitor/5.0/alpine/amd64/Dockerfile
> +    # Default Filter
The VerifyEnvironmentVariables test should be updated to cover these - https://github.com/dotnet/dotnet-docker/blob/main/tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs#L85.  

This shouldn't block the release but should be addressed before RTM.

2021-06-02 14:14 UTC, mthalman commented on src/monitor/5.0/alpine/amd64/Dockerfile
> +    # Default Filter
Logged https://github.com/dotnet/dotnet-docker/issues/2854

2021-06-02 15:35 UTC, jander-msft approved these changes

2021-06-02 23:01 UTC, jander-msft requested changes
@mthalman, we're requesting to cancel the release at this time to iron out an issue that we discovered. I'll sync up with you again in the near future when we're ready to release.

2021-06-03 13:32 UTC, mthalman commented
I'll keep this open for now and just update with the new changes.

2021-06-09 17:09 UTC, jander-msft commented
@mthalman, please merge the new dotnet-monitor version (5.0.0-preview.5.21302.5) from the nightly branch.

2021-06-09 17:33 UTC, mthalman commented
> @mthalman, please pull in the new dotnet-monitor version (5.0.0-preview.5.21302.5) from the nightly branch.

Thanks for the reminder.  Updated.

2021-06-09 23:22 UTC, jander-msft approved these changes

2021-06-10 13:57 UTC, merged