Breakup dotnet-monitor's entrypoint
dotnet/dotnet-docker pull request #3524
Opened 2022-02-25 21:10 UTC by kelltrick

Break's up `dotnet-monitor`'s `ENTRYPOINT` to more easily allow access to other `dotnet-monitor` commands and configurations.

2022-02-25 21:11 UTC, kelltrick commented
@jander-msft, here is the PR for dotnet/dotnet-monitor#1279

2022-02-28 16:33 UTC, jander-msft requested changes

2022-02-28 16:33 UTC, jander-msft commented on eng/dockerfile-templates/monitor/Dockerfile
> +ENTRYPOINT [ "dotnet-monitor" ]
This change needs to be conditioned so that it only applies to 7.0 and higher in order to not introduce a breaking change.

2022-02-28 16:33 UTC, jander-msft commented on eng/dockerfile-templates/monitor/Dockerfile
> +CMD [ "collect", "--urls", "https://+:52323", "--metricUrls", "http://+:52325" ]
Tests are failing due to this change. Please update the tests to understand that the `collect` command has been added to the `CMD` part of the image.

2022-03-01 03:34 UTC, jander-msft commented on eng/dockerfile-templates/monitor/Dockerfile
> +ENTRYPOINT [ "dotnet-monitor" ]
I would suggest moving the ENTRYPOINT and CMD into two separate templates (both containing their corresponding values for each directive) and then include either template based on the `dotnet monitor` version.

2022-03-03 20:05 UTC, jander-msft commented on eng/dockerfile-templates/monitor/Dockerfile
> +ENTRYPOINT [ "dotnet-monitor" ]
My suggestion was that you put

```
ENTRYPOINT [ "dotnet-monitor", "collect", "--urls", "https://+:52323", "--metricUrls", "http://+:52325" ]
````

in a separate template file named something like `Dockerfile.entrypoint.6` and then put

```
ENTRYPOINT [ "dotnet-monitor" ]
CMD [ "collect", "--urls", "https://+:52323", "--metricUrls", "http://+:52325" ]
```

in a separate template file named something like `Dockerfile.entrypoint.7`.

Then you can include it with one line, something like:

```
{{InsertTemplate(cat("Dockerfile.entrypoint.", monitorMajor))}}
```

This will make it easier to just say "this major version of dotnet monitor has this entrypoint" rather than describing it in terms of how the entrypoint changes from version to version. If 8.0.0 comes along with another differentiation, then it's easy to drop in a new file rather than refactoring the existing logic.

2022-03-03 20:05 UTC, jander-msft commented on tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs
> +            string cmdsToAdd = noAuthentication ? Switch_NoAuthentication : null;
Use a StringBuilder and start with the logic for adding Switch_DefaultImageCmd

2022-03-04 19:44 UTC, kelltrick commented on eng/dockerfile-templates/monitor/Dockerfile
> +    set fullEntrypoint to dotnetMajor = "6" ^
removed this and added `monitorMajor` up at the top.

2022-03-04 20:05 UTC, kelltrick commented on eng/dockerfile-templates/monitor/Dockerfile
> +ENTRYPOINT [ "dotnet-monitor" ]
This is done with templates now,

2022-03-04 20:12 UTC, kelltrick commented on eng/dockerfile-templates/monitor/Dockerfile
> +CMD [ "collect", "--urls", "https://+:52323", "--metricUrls", "http://+:52325" ]
I think the test changes will fix everything... We'll see.

2022-03-05 06:06 UTC, jander-msft approved these changes

2022-03-07 14:20 UTC, mthalman approved these changes

2022-03-07 20:33 UTC, merged