Add CBL Mariner 2.0 images in Arm64v8 for Monitor 6.2 and 7.0 images
dotnet/dotnet-docker pull request #3611
Opened 2022-04-01 23:30 UTC by kelltrick

Adds dotnet-monitor images:
- 6.2 dotnet-monitor, CBL Mariner 2.0, Arm64v8
- 7.0 dotnet-monitor, CBL Mariner 2.0, Arm64v8

2022-04-02 05:09 UTC, jander-msft requested changes
One correction that should also unblock the builds

2022-04-02 05:09 UTC, jander-msft commented on eng/mcr-tags-metadata-templates/monitor-tags.yml
> +$(McrTagsYmlTagGroup:7.0-cbl-mariner-arm64v8)
The CBL-Mariner images are undocumented, so these should not be added here

2022-04-04 15:56 UTC, kkeirstead commented on tests/performance/ImageSize.nightly.linux.json
> +    "src/monitor/6.2/cbl-mariner/arm64v8": 360000000,
Since we allow a range around the actual value this probably doesn't matter, but is there a reason why we're dropping precision for these?

2022-04-04 21:31 UTC, kkeirstead commented on eng/mcr-tags-metadata-templates/monitor-tags.yml
> +    customSubTableTitle: .NET Monitor Preview Tags10
I'm assuming this was accidental?

2022-04-04 21:33 UTC, mthalman commented
Make sure to run `eng/dockerfile-templates/Get-GeneratedDockerfiles.ps1`. Looks like the Dockerfiles you added are not up-to-date.

2022-04-05 17:46 UTC, jander-msft commented on tests/performance/ImageSize.nightly.linux.json
> +    "src/monitor/6.2/cbl-mariner/arm64v8": 360000000,
Not sure how to calculate these values locally since you cannot build arm64 images without arm64 hardware. Maybe we can check these in, wait for the images to be built, run the [size validation pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=379&_a=summary), and then update the baseline values from that run.

Maybe @mthalman has a better suggestion

2022-04-05 17:49 UTC, mthalman commented on tests/performance/ImageSize.nightly.linux.json
> +    "src/monitor/6.2/cbl-mariner/arm64v8": 360000000,
I usually run a build targeting a private branch to produce the images. But that seems overkill for this change. I think it's fine to just specify a good estimate of the size.

2022-04-08 05:53 UTC, jander-msft commented
Consider splitting this PR into two: one for the 6.2 addition and one for the 7.0 addition.
This will make it easier to port changes from nightly to main in the event that these two versions are shipped at different times.

2022-04-13 01:21 UTC, kelltrick commented on eng/mcr-tags-metadata-templates/monitor-tags.yml
> +    customSubTableTitle: .NET Monitor Preview Tags10
yep, that was a typo while I was deleting the doc line

2022-04-13 01:22 UTC, closed without merging