Doc to help determine action when CVE is reported
dotnet/dotnet-docker pull request #4181
Opened 2022-11-01 20:32 UTC by mthalman

Related to https://github.com/dotnet/dotnet-docker/issues/2787

2022-11-04 17:04 UTC, MichaelSimons reviewed
I like the direction you are headed @mthalman.  I realize this is still a draft but still felt it was worthwhile to share some thoughts/comments I had.

2022-11-04 18:52 UTC, mthalman commented on documentation/vulnerability-reporting.md
> +    docker pull <insert-my-image-digest>
I use that in the other script because that's specific to Linux containers. Your suggestion will fail if attempting to pull an image of a different OS type. So you may not even get to the point of running `docker inspect`. That's why the instructions here make the determination based on the error message or not.

2022-11-04 19:10 UTC, mthalman commented on documentation/vulnerability-reporting.md
> +flowchart
I would say no. You need a magnifying glass with horizontal.

2022-11-15 16:18 UTC, mthalman commented on documentation/vulnerability-reporting.md
> +docker manifest inspect <image-tag> | jq -r .mediaType
Experimental mode is [enabled by default](https://docs.docker.com/engine/reference/commandline/cli/#experimental-features) now. In fact, you can't even disable it: https://github.com/docker/cli/commit/977d3ae046ec6c64be8788a8712251ed547a2bdb. For that reason, I don't think it's worth mentioning.

2022-11-15 17:03 UTC, mthalman commented on documentation/vulnerability-reporting.md
> +baseImage="<insert-base-image-tag>"
Good suggestion. That was actually a very easy script to write.

2022-11-18 00:20 UTC, MichaelSimons reviewed
Looks great, I can wait to get this merged so we can start directing users to it.

2022-11-18 00:20 UTC, MichaelSimons commented on documentation/vulnerability-workflow.md
> +Requires [PowerShell](https://learn.microsoft.com/powershell/scripting/install/installing-powershell-on-linux) and [Syft](https://github.com/anchore/syft) to be installed.
Given the dependency on an external tool (e.g. syft), consider describing in a bit more detail how this can be verified manually.

2022-11-18 00:20 UTC, MichaelSimons commented on documentation/vulnerability-workflow.md
> +Requires [PowerShell to be installed](https://learn.microsoft.com/powershell/scripting/install/installing-powershell-on-linux).
The Syft dependency should be mentioned here in case the reader skips to this step.

2022-11-18 00:20 UTC, MichaelSimons commented on documentation/vulnerability-workflow.md
> +Log an issue at [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker) and provide the vulnerability ID and the .NET image tag you've identified as being affected.
Consider linking directly to the create issue page for convienence.

2022-11-18 00:20 UTC, MichaelSimons commented on documentation/vulnerability-workflow.md
> +Requires [PowerShell to be installed](https://learn.microsoft.com/powershell/scripting/install/installing-powershell-on-linux).
This is a PIA.  ...but I agree with the decision to get this out there to gauge value before investing further.

2022-11-22 16:22 UTC, mthalman commented on documentation/vulnerability-workflow.md
> +    LinuxFixAvailability --> |Yes|InLinuxBaseImage{J. Is package in<br>Linux distro<br>base image?}
I originally did that. But it led to a messy graph with lines crossing. I intentionally switched the yes/no sides for certain cases to optimize the placements of the boxes to produce a clean look.

2022-11-30 16:03 UTC, mthalman commented on documentation/vulnerability-workflow.md
> +To get the digest of your image, be sure to target a tag that is not a multi-arch/manifest list tag.
I will update this to be more informative on how to resolve the multi-arch tag. For your comment about pulling, that's specified in the next section: "Scan your latest image". This section isn't about what action to take. It's about determining the current state.

2022-11-30 20:02 UTC, mthalman commented on documentation/vulnerability-workflow.md
> +docker run --rm --entrypoint /bin/sh <image-name> -c "apt update > /dev/null && apt list --upgradable"
True but vulnerability scanners aren't currently going to find any vulnerabilities in chiseled images anyway right now. We'll have to come back to this once there is scanner support and that should help us determine a way forward on this.

2022-11-30 20:10 UTC, mthalman commented on documentation/vulnerability-workflow.md
> +Requires [PowerShell](https://learn.microsoft.com/powershell/scripting/install/installing-powershell-on-linux) and [Syft](https://github.com/anchore/syft) to be installed.
The whole intent of using Syft was to avoid describing in detail how to get this information. It's specific to each package manager type and distroless is a whole other mess to deal with. If the concern is about requiring the downloading of a 3rd party tool, I could change the script to make use of Syft's Docker image instead. Would that be better?

2022-11-30 22:27 UTC, MichaelSimons commented on documentation/vulnerability-workflow.md
> +Requires [PowerShell](https://learn.microsoft.com/powershell/scripting/install/installing-powershell-on-linux) and [Syft](https://github.com/anchore/syft) to be installed.
Yes, I think having a docker based solution would address my primary concern.

2022-11-30 22:27 UTC, MichaelSimons commented on documentation/vulnerability-workflow.md
> +docker run --rm --entrypoint /bin/sh <image-name> -c "apt update > /dev/null && apt list --upgradable"
Agreed, sounds reasonable.

2022-11-30 22:30 UTC, blowdart requested changes
You should also talk to Rich, given https://devblogs.microsoft.com/dotnet/investigating-a-linux-cve-with-net-images/

2022-11-30 22:30 UTC, blowdart commented on documentation/vulnerability-workflow.md
> +```
It's always fun to see security documentation recommending that you download and execute random files from github :)

Perhaps provide instructions for saving the ps1 files from the repo to the local drive too?

2022-11-30 22:30 UTC, blowdart commented on documentation/vulnerability-workflow.md
> +* If you're using an out-of-support .NET version, such as .NET 5, you'll need to upgrade your project and Dockerfiles to target a supported version.
Nit: need to => must. Stronger language is preferred.

Same for the points.

2022-11-30 22:30 UTC, blowdart commented on documentation/vulnerability-workflow.md
> +* If you're using a tag for a specific Windows version that is no longer supported, you'll need to move to a supported version of Windows. For example, `6.0-nanoserver-20H2` => `6.0-nanoserver-ltsc20
By adding specific version numbers here you're committing to updating this every month as 6.0 gets a new patch release, otherwise someone will point to this and say "This example says 6.0.9 is good". I realise this may seem unreasonable, but I've seen it happen.

2022-11-30 22:30 UTC, blowdart commented on documentation/vulnerability-workflow.md
> +A result of `False` means it is not built on the latest.
not built on the latest _and must be updated_

Yes, it's repetitive, but that's on purpose. People will skin to what to I run and what do the results mean.

2022-11-30 22:30 UTC, blowdart commented on documentation/vulnerability-workflow.md
> +Be sure that your workflow explicitly pulls the .NET base image tag rather than using a potentially cached version of it.
How? Cover azdo and actions perhaps?

2022-11-30 22:30 UTC, blowdart commented on documentation/vulnerability-workflow.md
> +Note whether the label indicates "High" or "Critical".
Not everyone uses CVSS unfortunately

2022-11-30 22:30 UTC, blowdart commented on documentation/vulnerability-workflow.md
> +The title or description of the vulnerability should indicate whether it's for .NET or not.
Bet :) It may be useful to point out CPEs, bugs in Microsoft products will always begin with

cpe:2.3:a:microsoft or, using the older CPE format  cpe:/a:microsoft

2022-11-30 22:30 UTC, blowdart commented on documentation/vulnerability-workflow.md
> +These occur on Patch Tuesday (the second Tuesday of each month).
Officially it's Update Tuesday :)

2022-11-30 22:37 UTC, MichaelSimons commented on documentation/scripts/check-latest-base.ps1
> +    $ImageTag,
I see a number of unresolved comments from my last review.  Not sure if they were overlooked or something you had a different view on.  I'm going to hold off on reviewing until I see a response.

2022-12-01 18:12 UTC, mthalman commented on documentation/vulnerability-workflow.md
> +```
> Perhaps provide instructions for saving the ps1 files from the repo to the local drive too?

Is that really necessary? If someone doesn't want to execute the script as is, surely they can be relied upon to know how to get the contents of the clearly visible URL onto their local machine.

2022-12-01 18:48 UTC, mthalman commented on documentation/vulnerability-workflow.md
> +Note whether the label indicates "High" or "Critical".
In that case then I doubt we'd get anyone coming to this repo about it then. All of the requests that I've ever received about vulnerabilities have been classified as high or critical.

2022-12-01 18:50 UTC, mthalman commented on documentation/vulnerability-workflow.md
> +The title or description of the vulnerability should indicate whether it's for .NET or not.
Given that this question is for the Windows path, all vulnerabilities would be Microsoft-related. This is specifically trying to narrow that down to with it is .NET-related or not.

2022-12-01 19:39 UTC, mthalman commented
I believe I've addressed all remaining comments.

In addition, I made an update to the flowchart to handle the scenario of a scanning tool reporting on a vulnerability for Linux. This was accounted for in the Windows path of the flowchart but not the Linux path. I've updated the chart to handle this. Linux is notable in this case because our images don't have Linux packages for .NET installed, we just have the extracted tarball which is what the scanning tools are looking for. So we need to handle that in the workflow before getting into the questioning about Linux packages.

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +curl -sSL https://raw.githubusercontent.com/dotnet/dotnet-docker/main/documentation/scripts/check-latest-bash.ps1 | pwsh /dev/stdin $myImage $dotnetBaseImage
```suggestion
curl -sSL https://raw.githubusercontent.com/dotnet/dotnet-docker/main/documentation/scripts/check-latest-base.ps1 | pwsh /dev/stdin $myImage $dotnetBaseImage
```

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/dotnet/dotnet-docker/main/documentation/scripts/check-latest-bash.ps1'))) $myImage $dotnetBaseImage
```suggestion
&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/dotnet/dotnet-docker/main/documentation/scripts/check-latest-base.ps1'))) $myImage $dotnetBaseImage
```

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +```powershell
I'm getting an error when executing this:

```
Exception calling "Create" with "1" argument(s): "At line:58 char:9
+         | Where-Object { $_.platform.Architecture -eq $imageConfig.Ar ...
+         ~
An empty pipe element is not allowed.
At line:59 char:9
+         | Select-Object -ExpandProperty digest
+         ~
An empty pipe element is not allowed."
At line:1 char:1
+ &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https:// ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
```

Here is the input I ran:

```
$myImage="mcr.microsoft.com/dotnet/samples@sha256:6274b2bdaba286678f4873a56194ea310f404ec9ae763e27a3d1a65f12ec5d26" # format: <registry>/<repo>@sha256:<digest>
$dotnetBaseImage="mcr.microsoft.com/dotnet/runtime-deps:7.0-alpine-amd64" # example: mcr.microsoft.com/dotnet/aspnet:7.0
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/dotnet/dotnet-docker/d18e5659ec1f95735a1706c76b69cfd71c4ffc86/documentation/scripts/check-latest-base.ps1'))) $myImage $dotnetBaseImage
```

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +imageName="<insert-linux-base-image-name>"
Consider adding an example here e.g. # example: alpine:3.17

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +curl -sSL https://raw.githubusercontent.com/dotnet/dotnet-docker/main/documentation/scripts/check-package-install.ps1 | pwsh /dev/stdin $imageName
Isn't this missing the package name?  Same applies to the windows snippet.

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +curl -sSL https://raw.githubusercontent.com/dotnet/dotnet-docker/main/documentation/scripts/check-package-install.ps1 | pwsh /dev/stdin $imageName
It would also be helpful to clarify the format of the package name e.g. the version numbers can be confusing to people who are not familiar with packages.

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +curl -sSL https://raw.githubusercontent.com/dotnet/dotnet-docker/main/documentation/scripts/check-package-install.ps1 | pwsh /dev/stdin $imageName
Same issue here as earlier, the package name option is missing

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +Check your Dockerfile to check how the package is being installed.
Avoiding using `Check` multiple times in this sentence.

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +Given that the vulnerability does not have a high severity, it will be addressed in the next .NET servicing release.
```suggestion
Given that the vulnerability does not have a critical or high severity, it will be addressed in the next .NET servicing release.
```

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +Contrast image digests with image tags which are mutable and cannot be relied upon for ensuring you're getting an exact version of the image every time.
This reads a little strange to me.

```suggestion
Contrasting image tags with image digests, image tags are mutable and cannot be relied upon for ensuring you're getting an exact version of the image every time.
```

2022-12-08 23:29 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +1. If you're using Docker Desktop for Windows, [change your settings](https://docs.docker.com/desktop/settings/windows/) to target Linux containers.
It will be interesting to see if we get feedback here from MacOS users.

2022-12-09 17:04 UTC, mthalman commented on documentation/vulnerability-reporting.md
> +```powershell
The digest you specified doesn't exist:

```
Pulling mcr.microsoft.com/dotnet/samples@sha256:6274b2bdaba286678f4873a56194ea310f404ec9ae763e27a3d1a65f12ec5d26...
Error response from daemon: manifest for mcr.microsoft.com/dotnet/samples@sha256:6274b2bdaba286678f4873a56194ea310f404ec9ae763e27a3d1a65f12ec5d26 not found: manifest unknown: manifest sha256:6274b2bdaba286678f4873a56194ea310f404ec9ae763e27a3d1a65f12ec5d26 is not found
```

Can you provide a valid one? I'm unable to reproduce what you're seeing with the ones I've tried.

2022-12-09 21:49 UTC, mthalman commented on documentation/vulnerability-reporting.md
> +1. If you're using Docker Desktop for Windows, [change your settings](https://docs.docker.com/desktop/settings/windows/) to target Linux containers.
It shouldn't matter. The only cases you need to actually run containers locally is when you're investigating a vulnerability in a Linux container. So the instructions are valid for all OS types.

2022-12-09 21:51 UTC, mthalman commented on documentation/vulnerability-reporting.md
> +&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/dotnet/dotnet-docker/main/documentation/scripts/check-tag-support.ps1'))) $dotnetImage
This was because I added strict mode after testing it. Doh. Fixed.

2022-12-09 21:51 UTC, mthalman commented on documentation/vulnerability-reporting.md
> +curl -sSL https://raw.githubusercontent.com/dotnet/dotnet-docker/main/documentation/scripts/check-package-install.ps1 | pwsh /dev/stdin $imageName
This is added in section J.

2022-12-09 22:39 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +But this indicates the name of the source package, not the name of the binary package that would be installed in an image.
Consider referencing the distro's package manager here.

```suggestion
But this indicates the name of the source package, not the name of the binary package that would be installed from the distro's package manager.
```

2022-12-09 22:39 UTC, MichaelSimons commented on documentation/vulnerability-reporting.md
> +```powershell
I am still getting the same error.  This time I validated the sha was valid.

``` bash
> docker pull mcr.microsoft.com/dotnet/samples@sha256:e59ce8b5c10e0676f60954fab0494fcc27d845bd15bf08ccde996305f44fadb7
mcr.microsoft.com/dotnet/samples@sha256:e59ce8b5c10e0676f60954fab0494fcc27d845bd15bf08ccde996305f44fadb7: Pulling from dotnet/samples
Digest: sha256:e59ce8b5c10e0676f60954fab0494fcc27d845bd15bf08ccde996305f44fadb7
Status: Downloaded newer image for mcr.microsoft.com/dotnet/samples@sha256:e59ce8b5c10e0676f60954fab0494fcc27d845bd15bf08ccde996305f44fadb7
mcr.microsoft.com/dotnet/samples@sha256:e59ce8b5c10e0676f60954fab0494fcc27d845bd15bf08ccde996305f44fadb7
```

``` bash
PS C:\Users\msimons\Downloads> $myImage="mcr.microsoft.com/dotnet/samples@sha256:e59ce8b5c10e0676f60954fab0494fcc27d845bd15bf08ccde996305f44fadb7" # format: <registry>/<repo>@sha256:<digest>
PS C:\Users\msimons\Downloads> $dotnetBaseImage="mcr.microsoft.com/dotnet/runtime-deps:7.0-alpine-amd64" # example: mcr.microsoft.com/dotnet/aspnet:7.0
PS C:\Users\msimons\Downloads> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
PS C:\Users\msimons\Downloads> &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/dotnet/dotnet-docker/d18e5659ec1f95735a1706c76b69cfd71c4ffc86/documentation/scripts/check-latest-base.ps1'))) $myImage $dotnetBaseImage
Exception calling "Create" with "1" argument(s): "At line:58 char:9
+         | Where-Object { $_.platform.Architecture -eq $imageConfig.Ar ...
+         ~
An empty pipe element is not allowed.
At line:59 char:9
+         | Select-Object -ExpandProperty digest
+         ~
An empty pipe element is not allowed."
At line:1 char:1
+ &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https:// ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
```

2022-12-13 19:47 UTC, MichaelSimons approved these changes

2022-12-14 17:02 UTC, merged