Enable Composite Docker Images for Jammy Chiseled and Mariner Distroless
dotnet/dotnet-docker pull request #4710
Opened 2023-06-29 22:51 UTC by ivdiazsa

This PR is a follow-up to #4594. Now, we're looking to also build the Jammy Chiseled and Mariner Distroless flavors of the composite.

2023-06-29 22:51 UTC, ivdiazsa commented
@lbussell @mangod9 @trylek

2023-06-29 22:55 UTC, trylek reviewed
Thanks Ivan for pulling this off! The change looks good to my limited understanding but I'd definitely welcome docker people to take a closer look at the various details, I'm not really that much familiar with the template system. Please also rebase your change against the latest main, in the current form your PR shows as blocked on conflicts and cannot be merged in.

2023-06-30 02:29 UTC, mangod9 commented
yeah would be good to get a review from @lbussell, @mthalman et. al. @richlander fyi.

2023-06-30 02:58 UTC, richlander commented
Thanks!

Do you have size diffs to share?

2023-06-30 12:50 UTC, mthalman commented on src/aspnet/8.0/cbl-mariner2.0-distroless-composite/amd64/Dockerfile
> +
Remove trailing line

2023-06-30 12:50 UTC, mthalman commented on eng/dockerfile-templates/aspnet/Dockerfile.linux-composite
> +# .NET Runtime-Deps Image
This should be reverted. We want it to be `ASP.NET Composite Runtime Image`. To clarify, this comment should refer to what the stage produces, not what it's based on.

2023-06-30 15:48 UTC, mangod9 commented
> Thanks!
> 
> Do you have size diffs to share?

should be an absolute ~9mb reduction for x64 and ~12mb for arm64.

2023-06-30 16:26 UTC, richlander commented
Nice @mangod9  ... Can one of you add that context to the initial PR comment so that it is obvious?

2023-06-30 18:01 UTC, ivdiazsa commented
Something might have gone wrong with the updating with the nightly branch. Looking at it now

2023-06-30 18:01 UTC, mthalman commented
I just merged what should be the last update for Preview 6. So you'll need to merge changes from nightly again and update the SHAs for the composite files in the manifest.versions.json, based on that new build. Then also regenerate Dockerfiles.

2023-07-01 00:35 UTC, lbussell commented on eng/dockerfile-templates/aspnet/Dockerfile.linux-composite
>          "is-rpm-install": isRpmInstall,
We can probably clean up the `isRpmInstall` variable from this file, I think cbl mariner for 6.0 is the only one that uses this option. It's left over from me copying from the runtime template. It would clean up a lot of the conditionals in this file.

2023-07-01 00:35 UTC, lbussell commented on src/aspnet/8.0/alpine3.18-composite/amd64/Dockerfile
>      && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
We also want to keep the newline at the end of these files

2023-07-01 00:35 UTC, lbussell commented on src/aspnet/8.0/cbl-mariner2.0-distroless-composite/amd64/Dockerfile
> +CMD ["--info"]
Newline here please

2023-07-01 00:36 UTC, lbussell commented
When the PR is green again I can queue an internal build and update the baseline here. Nice job on the templates @ivdiazsa.

2023-07-05 19:48 UTC, ivdiazsa commented on src/aspnet/8.0/cbl-mariner2.0-distroless-composite/amd64/Dockerfile
> +CMD ["--info"]
But there was a newline before and Matt asked me to remove it.

2023-07-05 19:59 UTC, lbussell commented on src/aspnet/8.0/cbl-mariner2.0-distroless-composite/amd64/Dockerfile
> +CMD ["--info"]
Oh, right, GitHub messes with the rendering, looking at it in the editor it looks correct.

2023-07-05 19:59 UTC, lbussell commented on src/aspnet/8.0/alpine3.18-composite/amd64/Dockerfile
>      && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
I think this is actually correct.

2023-07-06 16:37 UTC, lbussell requested changes

2023-07-06 16:37 UTC, lbussell commented on manifest.json
> +                "REPO": "$(Repo:runtime)"
```suggestion
                "REPO": "$(Repo:runtime-deps)"
```

We don't want to base this on the runtime image, since the aspnet composite tarball contains its own runtime.

2023-07-06 16:37 UTC, lbussell commented on manifest.json
> +                "REPO": "$(Repo:runtime)"
Same goes for all other new manifest entries.

2023-07-06 20:21 UTC, ivdiazsa commented on manifest.json
> +                "REPO": "$(Repo:runtime)"
Oops I must've missed it when duplicating the template. Thanks for addressing it Logan!

2023-07-06 23:26 UTC, lbussell approved these changes

2023-07-07 13:51 UTC, mthalman approved these changes
Since we're so close to Preview 6 release, we'll get this shipped in Preview 7. So let's hold off on merging this into nightly until after the Preview 6 release just to minimize the management of diffs between the branches.

2023-07-12 16:49 UTC, mangod9 commented
@mthalman just checking if the preview6 release is done, so we could get this merged?

2023-07-12 20:51 UTC, merged

2023-07-12 20:53 UTC, mangod9 commented
Thanks Matt!