Dev/wiktork/prepare dotnet monitor
dotnet/dotnet-docker pull request #4972
Opened 2023-10-27 16:38 UTC by wiktork

2023-10-27 16:41 UTC, jander-msft requested changes

2023-10-27 16:41 UTC, jander-msft commented on manifest.versions.json
> +    "monitor|8.0|build-version": "8.0.0",
This needs to be the unstable/non-final version (e.g. 8.0.0-rtm.23526.10). Using `.\eng\Set-DotnetVersions.ps1 8.0 -MonitorVersion 8.0.0-rtm.23526.10 -UseStableBranding` should achieve this.

2023-10-27 16:41 UTC, jander-msft commented on src/monitor-base/8.0/cbl-mariner-distroless/amd64/Dockerfile
>      && dotnet_monitor_base_sha512='b024c1871061b8ec03e26af2ee8fe28cdfcc5c64f7c6bfbbdea143c37fe2a16b671b6a880e84f5b73d84a5d28f7b227ead76549b74e60be561a377eff6b32bce' \
The updater didn't update the checksums because it couldn't find the 8.0.0 version; using the unstable/non-final version will allow it to locate it.

2023-10-27 16:54 UTC, jander-msft approved these changes

2023-10-30 19:06 UTC, lbussell approved these changes

2023-10-30 19:06 UTC, merged