Add support for Azure Linux 3.0
dotnet/dotnet-docker pull request #5359
Opened 2024-04-12 19:44 UTC by MichaelSimons

Related to https://github.com/dotnet/dotnet-docker/issues/5331

- [ ] update image-builder
- [ ] update manifest
- [ ] generated dockerfiles
- [ ] update size baseline
- [ ] update/add tests
- [ ] generate readmes
- [ ] use public ACR base images
- [ ] rename mariner template files
- [ ] rename azure-linux to azurelinux

2024-04-12 19:58 UTC, lbussell commented
Can you open a tracking issue in dotnet/release with the template ".NET Docker Release - New Linux Distro" for this? It contains a more detailed checklist.

2024-04-15 14:14 UTC, MichaelSimons commented
> Can you open a tracking issue in dotnet/release with the template ".NET Docker Release - New Linux Distro" for this? It contains a more detailed checklist.

https://github.com/dotnet/release/issues/901 - That checklist is out of date - no Dockerfile templates.  I will update when done.

2024-04-16 19:28 UTC, MichaelSimons commented
This is ready for review feedback.

2024-04-16 20:34 UTC, mthalman requested changes

2024-04-16 20:34 UTC, mthalman commented on tests/Microsoft.DotNet.Docker.Tests/OS.cs
> +        public const string AzureLinux30 = $"{AzureLinux}2.0";
```suggestion
        public const string AzureLinux30 = $"{AzureLinux}3.0";
```

2024-04-17 13:53 UTC, mthalman approved these changes

2024-04-17 16:02 UTC, mthalman approved these changes

2024-04-17 16:40 UTC, jander-msft approved these changes

2024-04-17 20:49 UTC, merged