Define new version manifest variables
dotnet/dotnet-docker pull request #5586
Opened 2024-06-20 15:42 UTC by mthalman

This extends the version variable pattern that already exists for .NET 9 (originally introduced in https://github.com/dotnet/dotnet-docker/pull/5039) to the entire manifest. This gets all repos and versions consistent with their version variable usage.

This allows for the ability to more easily change names in one location. See https://github.com/dotnet/dotnet-docker/pull/5579#discussion_r1646521607.

2024-06-20 16:06 UTC, MichaelSimons approved these changes

2024-06-27 18:08 UTC, mthalman commented on README.sdk.md
> +6.0.423-bullseye-slim-amd64, 6.0-bullseye-slim-amd64, 6.0.423-bullseye-slim, 6.0-bullseye-slim, 6.0.423, 6.0 | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/nightly/src/sdk/6.0/bullseye-s
This ended up fixing a mistake from https://github.com/dotnet/dotnet-docker/pull/5614 that didn't remove the `-1` from the `6.0.423` tag.

2024-06-27 18:44 UTC, MichaelSimons approved these changes

2024-07-01 17:24 UTC, lbussell requested changes
Tags in `customBuildLegGroups` need to be updated for .NET 6 and 8. Example from 9.0: https://github.com/dotnet/dotnet-docker/blob/56dad2cfdbc0a0e3d728a34f2934f5ccf5551a0c/manifest.json#L2028

2024-07-03 22:49 UTC, lbussell approved these changes
:shipit:

2024-07-03 23:42 UTC, lbussell commented
Needed to re-do the Alpine 3.20 work in order to get a clean merge here. I also caught the `extra`, `aot`, and `composite` variants floating tags were not moved to 3.20. So this includes that change as well.

2024-07-04 00:55 UTC, merged