Add syft updater
dotnet/dotnet-docker pull request #5769
Opened 2024-08-08 21:27 UTC by NikolaMilosavljevic

Fixes: https://github.com/dotnet/dotnet-docker/issues/4545

Adds a simple syft updater.

2024-08-09 12:46 UTC, mthalman approved these changes

2024-08-09 13:39 UTC, lbussell requested changes
Please base this off of nightly - the update dependencies code for updating based off of GitHub releases has changed substantially in the past month.

It has not made it into main yet since servicing is next week and the tool is never called from main.

2024-08-09 17:55 UTC, NikolaMilosavljevic commented
> Please base this off of nightly - the update dependencies code for updating based off of GitHub releases has changed substantially in the past month.
> 
> It has not made it into main yet since servicing is next week and the tool is never called from main.

Fixed with https://github.com/dotnet/dotnet-docker/pull/5769/commits/ad5d4e5cd5f8e6d984ec2ac38e640986a58cb27f

I've rebased and force-pushed the change.

2024-08-09 21:02 UTC, lbussell commented on eng/update-dependencies/SyftUpdater.cs
> +using System.Text.RegularExpressions;
```suggestion
```

These imports appear to be unused.

2024-08-09 21:58 UTC, NikolaMilosavljevic commented on eng/update-dependencies/SyftUpdater.cs
> +using System.Text.RegularExpressions;
Fixed with https://github.com/dotnet/dotnet-docker/pull/5769/commits/810c6cd1a6e65ea350b4878c464d2d831217e9ca

2024-08-12 15:01 UTC, lbussell approved these changes

2024-08-12 15:02 UTC, merged