Latest Tag Static Validation Tests
dotnet/dotnet-docker pull request #5852
Opened 2024-09-03 17:17 UTC by ellahathaway

This PR is part of the logic needed to complete https://github.com/dotnet/dotnet-docker/issues/5838.

**Tests for Latest Tags**
In `StaticTagTests.cs`, this PR introduces tests to ensure adherence to the latest tag rules:

- `LatestTag_OnePerRepo`: Verifies that there is only one latest tag per repository.
- `LatestTag_IsNotPlatformSpecific`: Ensures the latest tag is a shared-tag and is not specified in any platform's tags.
- `LatestTag_OnCorrectMajorVersion`: Confirms that the latest tag points to the expected major version for each repo.

**Parsing Logic for Image-Builder Manifest**
In `ManifestHelper.cs`, this PR adds logic to parse the image-builder manifest into a format suitable for testing.

2024-09-03 18:16 UTC, mthalman commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                $"Expected a single image with the shared latest tag, but found {latestTagImages.Count}.");
```suggestion
            Assert.Single(latestTagImages);
```

2024-09-03 18:16 UTC, mthalman commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                    $"  {string.Join("\n", latestTagPlatforms.Select(platform => platform.Dockerfile))}");
```suggestion
                Assert.Empty(latestTagPlatforms);
```

2024-09-03 18:16 UTC, mthalman commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +            Assert.True(productVersions.Count > 0, "No product versions found for repo.");
```suggestion
            Assert.NotEmpty(productVersions);
```

2024-09-03 18:16 UTC, mthalman commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                return productVersions.OrderByDescending(version => version).ElementAt(1);
This will fail on the GA release because we will move `latest` to point to 9.0 at that time.

2024-09-03 18:26 UTC, ellahathaway commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                return productVersions.OrderByDescending(version => version).ElementAt(1);
Ah you're right. I was thinking that we'd add 10.0 alpha at the same time that we GA for 9.0, but we don't add anything for 10.0 until it's in preview, correct?

2024-09-03 18:29 UTC, ellahathaway commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +            LatestTag_OnCorrectMajorVersion(repo);
This was my original implementation, but as I added the tests for the tag schema validation, the number of tests being run became quite large. If we're okay that larger number, then I'm alright with splitting these into separate tests.

2024-09-03 18:31 UTC, mthalman commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +            LatestTag_OnCorrectMajorVersion(repo);
I'm not concerned about a large number of tests. The checks are still being run either way. Benefits of having these as separate tests:
* They get run in parallel
* If one fails, it won't block seeing the results of others

2024-09-03 18:35 UTC, mthalman commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                return productVersions.OrderByDescending(version => version).ElementAt(1);
Correct, 10.0 wouldn't exist in the main branch until its Preview 1 release next year.

2024-09-03 18:42 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/ManifestHelper.cs
> +            JsonConvert.DeserializeObject<SimplifiedManifest>(Config.Manifest.Value.ToString())!;
Wouldn't deserializing the manifest get us most of the way towards https://github.com/dotnet/dotnet-docker/issues/5337 as well? It's not like deserialization code can't be re-used in this project. The JsonConverter approach may be more complicated than necessary for this use case but I don't see a big problem with deserializing in general. Do you think all future scenarios involving the manifest in these test should use Json node API?

IF we were deserializing here, I would expect just plain old classes and resolve the variables as necessary using the existing helper methods.

2024-09-03 18:44 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                return productVersions.OrderByDescending(version => version).ElementAt(1);
We can add it in Alpha, but these tests should not assume that there is a preview version.

2024-09-03 19:54 UTC, ellahathaway commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                return productVersions.OrderByDescending(version => version).ElementAt(1);
[This new logic](https://github.com/dotnet/dotnet-docker/pull/5852/files#diff-ba5f21c7428ca6e5f48f4fc38a102bb329c13fba9e07684b94a6d5b29f2c5e50R84) should work; for nightly it takes the greatest version listed, and for main it takes the greatest GA version (any version without a `-`). I validated the logic in main by changing the latest 9.0 sdk product version from 9.0.100-rc.1 to 9.0.0, and the test failed as expected.

2024-09-04 12:51 UTC, mthalman approved these changes

2024-09-04 12:51 UTC, mthalman commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                    .Where(version => !version.Contains("-"))
This would benefit from a comment explaining what the goal is here.

2024-09-04 16:18 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +            var latestTagImages = repo.Images
Nit: use explicit types where it's not immediately obvious what the type is (I have to hover to figure out if this is strings, or Images, etc.). Also applies to some other tests.

2024-09-04 16:18 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                .ToList();
The `ToList()` call here is unnecessary since Xunit's `Assert.Single` takes an `IEnumerable`. Applies to other tests as well.

2024-09-04 16:18 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +            var expectedMajorVersion = GetExpectedMajorVersion(repo);
Nit: use explicit types for built-in types (primitives). This reads as ambiguous between int or string.

2024-09-04 16:18 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                .Select(image => ManifestHelper.GetResolvedProductVersion(image))
My IDE points out that this is an unnecessary lambda:

```suggestion
                .Select(ManifestHelper.GetResolvedProductVersion)
```

2024-09-04 16:18 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +            {
Avoid cascading if statements/unnecessary else clauses. Since each case here returns from the method, this could be formatted as:

```
if foo:
    return thing1;

if bar:
    return thing2;

return thing3;
```

2024-09-04 16:18 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                    .Where(version => !version.Contains("-"))
Agree, the three different string-split operations could each have explanations here.

2024-09-04 16:18 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +        private string GetExpectedMajorVersion(ManifestHelper.Repo repo)
```suggestion
        private static string GetExpectedMajorVersion(ManifestHelper.Repo repo)
```

2024-09-04 16:18 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                return majorVersions.Max()!;
Prefer not to use the null-forgiving operator. If the method can return null then change the method signature to have nullable annotation. Otherwise if the method shouldn't return null, throw an exception with a detailed comment (or, use an assertion here since this is a test after all).

2024-09-04 18:39 UTC, ellahathaway commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                return majorVersions.Max()!;
I understand your point; however, I have already asserted that the product versions are not empty using `Assert.NotEmpty(productVersions)`;. Given this assumption, `majorVersions.Max()` is guaranteed to return a value since it only parses the major version numbers from the product versions. While I could assert that `version.Split('.')[0]` is not null, it seems excessive because, in my opinion, it is an axiom that the version number will contain at least one period.

2024-09-04 19:39 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                return majorVersions.Max()!;
OK, that's fine then. I'm good with the null-forgiving operator in this case.

2024-09-04 23:36 UTC, ellahathaway commented on tests/Microsoft.DotNet.Docker.Tests/ManifestHelper.cs
> +        public class SimplifiedManifest
Sure, that makes sense.

2024-09-04 23:57 UTC, ellahathaway commented on tests/Microsoft.DotNet.Docker.Tests/ManifestHelper.cs
> +        public class SimplifiedManifest
I created [this separate file](https://github.com/dotnet/dotnet-docker/pull/5852/files#diff-90167091f8a14aab39fa3a5793ec468b92725a4bb9485284c4bc157a17c2d885) for the classes, but I feel a little odd about all of the classes being in this single file. What are your thoughts on either nesting the classes, leaving this file as is, creating separate files for each of the classes?

2024-09-06 16:00 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +        public StaticTagTests(ITestOutputHelper outputHelper) => OutputHelper = outputHelper;
OutputHelper seems unused here? Can it be removed?

2024-09-06 17:13 UTC, lbussell requested changes

2024-09-06 17:13 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                return majorVersions.Max() ?? throw new Exception("No latest product versions found.");
This calling `IEnumerable<string>.Max()`. That means it'll return `"9"` as max when we have .NET versions `["8", "9", "10"]`. Instead, `GetMajorVersion` should probably parse the string as an int before returning.

2024-09-06 17:13 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +            return gaVersions.Max() ?? throw new Exception("No GA product versions found.");
This could have a more descriptive error message.
```suggestion
            return gaVersions.Max()
                ?? throw new Exception($"Did not find any GA product versions for repo ${repo}");
```

2024-09-06 17:13 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/Manifest.cs
> +    public class Repo
Consider using Records for these model classes, as they have automatically implemented ToString() methods - helps with logging and debugging.

```suggestion
    public record Repo
```

2024-09-06 17:13 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/ManifestHelper.cs
> +            return Config.GetVariableValue(variableName) + remainingString;
This only matches tags of the pattern `$(foo)*`. We should be free to create tags using variables at any point in the string, such as `$(foo)-$(bar)-$(baz)-extra`. Consider iterating over each variable regex match when replacing values here.

2024-09-06 17:13 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +                .Where(version => !version.Contains('-'))
I think the comment should point out that this is just a heuristic for finding the latest GA major version. We are assuming that GA versions will look like `9.0` and non-GA versions will look like `9.0-preview.7` or `9.0-rc.1`. That assumption is Good Enough but it should be noted here.

2024-09-06 17:22 UTC, ellahathaway commented on tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
> +            return gaVersions.Max() ?? throw new Exception("No GA product versions found.");
The exception is no longer needed after converting the function to return an int.

2024-09-06 17:46 UTC, ellahathaway commented on tests/Microsoft.DotNet.Docker.Tests/Manifest.cs
> +    public class Repo
I tried this, and Json deserialization did not work as expected. After doing a little research, I learned that I'd have to write additional constructors in order for the deserialization to work. That feels a bit unnecessary, so I'm choosing to leave them as classes.

2024-09-06 18:41 UTC, merged