Add Aspire Dashboard 9.0 image
dotnet/dotnet-docker pull request #6038
Opened 2024-11-07 23:31 UTC by joperezr

Adding a draft PR that will help ship the aspire-dashboard for .NET Aspire 9.0

cc: @lbussell

2024-11-07 23:32 UTC, joperezr commented
@lbussell should I also remove the 8.x image in this PR?

2024-11-09 00:07 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/AspireDashboardImageTests.cs
> +
Can be removed since we won't ship Aspire Dashboard 8.X anymore.
```suggestion
```

2024-11-09 00:07 UTC, lbussell commented on tests/Microsoft.DotNet.Docker.Tests/AspireDashboardImageTests.cs
>              // to have a base URL of 0.0.0.0 due to a bug in the Aspire Dashboard.
```suggestion
```

2024-11-09 00:07 UTC, lbussell commented on tests/performance/ImageSize.nightly.linux.json
> +    "src/aspire-dashboard/8.2/cbl-mariner-distroless/arm64v8": 148315271,
Can be removed.

2024-11-09 00:07 UTC, lbussell commented on manifest.versions.json
> +    "aspire-dashboard|9.0|product-version": "9.0.0-preview.5",
I was expecting this to contain the versions:

```suggestion
    "aspire-dashboard|9.0|build-version": "9.0.0",
    "aspire-dashboard|9.0|product-version": "9.0.0",
```

And for the shas to be for the binaries that will be released when it that version goes live (I did not check if these shas match version `9.0.0-preview.5`).

2024-11-11 23:46 UTC, joperezr commented on manifest.versions.json
> +    "aspire-dashboard|9.0|product-version": "9.0.0-preview.5",
Updated based on your suggestion, and the shas should be accurate.

2024-11-12 18:36 UTC, lbussell requested changes

2024-11-12 18:36 UTC, lbussell commented on README.aspire-dashboard.md
> +  * `docker pull mcr.microsoft.com/dotnet/aspire-dashboard:8.2`
Should be `9.0`

2024-11-12 18:36 UTC, lbussell commented on README.aspire-dashboard.md
> +9.0.0-preview.5, 9.0, 9, latest | [Dockerfile](src/aspire-dashboard/9.0/cbl-mariner-distroless/arm64v8/Dockerfile) | CBL-Mariner 2.0
Looks like readmes need to be re-generated since these still reference preview 5.

2024-11-12 21:07 UTC, lbussell commented
/azp run

2024-11-12 21:23 UTC, lbussell approved these changes

2024-11-12 21:37 UTC, merged