Re-write ASP.NET Core HTTPS documentation
dotnet/dotnet-docker pull request #6117
Opened 2024-12-16 22:18 UTC by lbussell

Fixes #5113

While working on #5113 I noticed that the two documents, `run-aspnetcore-https-development.md` and `host-aspnetcore-https.md` contained much of the same information. I tried to combine them and improve both documents in the process.

A couple of other notes:
- I couldn't get `Kestrel:Certificates:Development:Password` or `ASPNETCORE_Kestrel__Certificates__Development__Password` to work for any scenario. Only `Default` worked.
- I couldn't get any sample image to read a certificate from `/home/app/.aspnet/https/aspnetapp.pfx`, so I made all the example commands specific the exact path to the certificate. I think this is clearer anyways.

2024-12-17 00:48 UTC, richlander commented
These docs pre-date the official docs: https://learn.microsoft.com/aspnet/core/security/enforcing-ssl

Ideally, we'd rely as much as possible on the official docs. Either way, we should get the ASP.NET Core team to sign off on the changes.

@javiercn @Rick-Anderson

2024-12-17 15:31 UTC, lbussell commented
> These docs pre-date the official docs: https://learn.microsoft.com/aspnet/core/security/enforcing-ssl
> 
> Ideally, we'd rely as much as possible on the official docs. Either way, we should get the ASP.NET Core team to sign off on the changes.
> 
> @javiercn @Rick-Anderson

Yes, I did find those, and they seemed very similar to these docs. Worth noting that [Hosting ASP.NET Core images with Docker over HTTPS](https://learn.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-9.0#running-pre-built-container-images-with-https) links to `run-aspnetcore-https-development.md` at the bottom of the document.

I would love to throw out `host-aspnetcore-https.md` and link to the learn.microsoft.com documentation. Not sure how others feel about that.

2024-12-17 22:30 UTC, mthalman commented
I'm fine with getting rid of these files and updating the existing links to them to point to the docs site instead.

2024-12-20 13:41 UTC, mthalman reviewed
Why are we having two files that have the same content?

2024-12-20 15:16 UTC, lbussell commented
> Why are we having two files that have the same content?

I don't know, I didn't create them initially. They don't have the same content anymore.

I chose to leave the files in case there are links to them from other places. For example, [run-aspnetcore-https-development.md](https://github.com/dotnet/dotnet-docker/blob/main/samples/run-aspnetcore-https-development.md) is referenced from [Hosting ASP.NET Core images with Docker over HTTPS](https://learn.microsoft.com/aspnet/core/security/docker-https). If you think we should delete the file and change the docs website then we can also do that.

2024-12-20 16:04 UTC, mthalman commented
> They don't have the same content anymore.

Weird. I don't know what I was doing but when I looked at them they were identical.

2024-12-20 16:17 UTC, mthalman commented on samples/run-aspnetcore-https-development.md
> +    # Use user secrets instead of certificate password environment variable
The comments here mess up the multi-line PowerShell. It essentially breaks the line continuations that are used causing an invalid command when pasting this whole thing.

2024-12-23 18:34 UTC, Rick-Anderson commented on samples/host-aspnetcore-https.md
> +identity, and encryption.
```suggestion
ASP.NET Core uses [HTTPS by default](https://docs.microsoft.com/aspnet/core/security/enforcing-ssl). [HTTPS](https://en.wikipedia.org/wiki/HTTPS) relies on [certificates](https://en.wikipedia.org/wiki/Public_key_certificate) for trust, identity, and encryption.
```

2024-12-23 23:58 UTC, Rick-Anderson requested changes

2024-12-23 23:58 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +the latest version.
```suggestion
This example requires [Docker Desktop](https://www.docker.com/products/docker-desktop/). We recommend the latest version.
```

2024-12-23 23:58 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +from [Running pre-built container images with HTTPS](https://learn.microsoft.com/aspnet/core/security/docker-https#running-pre-built-container-images-with-https).
```suggestion
Follow the instructions for creating a [.NET development certificate](https://learn.microsoft.com/dotnet/core/tools/dotnet-dev-certs) from [Running pre-built container images with HTTPS](https://learn.microsoft.com/aspnet/core/security/docker-https#running-pre-built-container-images-with-https).
```

2024-12-23 23:58 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +certificate password, continue reading.
```suggestion
See [Hosting ASP.NET Core images with Docker over HTTPS](https://learn.microsoft.com/aspnet/core/security/docker-https). See the following section if you don't want to use environment variables to store your development
certificate password.
```

2024-12-23 23:58 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +instead to store the certificate password on your machine.
```suggestion
Rather than using environment variable to specify the development certificate password,  use [.NET user secrets](https://learn.microsoft.com/aspnet/core/security/app-secrets) to store the password.
```

2024-12-23 23:58 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +this repo or [download the repository as a zip](https://github.com/dotnet/dotnet-docker/archive/main.zip).
```suggestion
Using User Secrets requires modifications to the `aspnetapp` sample. Clone
this repo or [download the repository as a zip](https://github.com/dotnet/dotnet-docker/archive/main.zip).
```

2024-12-23 23:58 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +First, initialize user secrets for your app, and set the certificate password.
```suggestion
Initialize user secrets for your app, and set the certificate password:
```

2024-12-23 23:58 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<CREDENTIAL_PLACEHOLDER>"
Per SFI, credential instructions can't be copy/paste ready. Add illegal strings so they can't have a working copy/paste. 

```suggestion
dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
```

2024-12-23 23:58 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +project file, so we need to re-build the sample image:
```suggestion
Initializing user-secrets for the first time on a project modifies the project file, which requires re-building the sample image:
```

2024-12-23 23:58 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +
```suggestion
In Linux containers, .NET looks under the `~/.microsoft/usersecrets/` directory for user secrets data. Bind-mount your host machine's user secrets directory to the container's filesystem. This is similar to the preceding certificate instructions. f you are running your container as the `root` user, replace `/home/app/` with the `root` user's home directory, `/root/`.
```

2025-01-06 18:28 UTC, mthalman commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
The `<CREDENTIAL_PLACEHOLDER>` change needs to be reverted. It is specifically defined that way as a magic string to appease the secrets scanner.

2025-01-06 18:30 UTC, lbussell commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
Can we validate that this new format won't trip the secret scanner? Or find another way to break the command so that it can't be copy-pasted without changes?

2025-01-06 18:34 UTC, mthalman commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
Don't know. It gets executed automatically on the server side when attempting to push into the AzDO repo.

2025-01-06 18:41 UTC, lbussell commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
I was able to push this branch internally without issue: https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet-docker?path=/samples/run-aspnetcore-https-development.md&version=GBdev/loganbussell/pulls/6117&line=51&lineEnd=52&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

2025-01-06 18:57 UTC, mthalman commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
Ok, that's good. But I don't understand the need for the change. It's not formatted correctly. It leads to this error: `Unrecognized command or argument 'PLACEHOLDER>'`

2025-01-06 20:46 UTC, lbussell commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
My interpretation of Rick's suggestion is that the command _shouldn't_ be formatted correctly. It should error if users copy-paste without changing the placeholder text, to prevent them from using `<CREDENTIAL_PLACEHOLDER>` as the password.

2025-01-06 20:52 UTC, mthalman commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
> My interpretation of Rick's suggestion is that the command _shouldn't_ be formatted correctly. It should error if users copy-paste without changing the placeholder text, to prevent them from using `<CREDENTIAL_PLACEHOLDER>` as the password.

@Rick-Anderson - Is that the case here and if so, is that a common pattern used in our docs? I'm concerned that users will get confused by this syntax and think that things need to be formatted in special way rather than just a simple string.

2025-01-06 21:00 UTC, Rick-Anderson commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
> > My interpretation of Rick's suggestion is that the command _shouldn't_ be formatted correctly. It should error if users copy-paste without changing the placeholder text, to prevent them from using `<CREDENTIAL_PLACEHOLDER>` as the password.
> 
> @Rick-Anderson - Is that the case here and if so, is that a common pattern used in our docs? I'm concerned that users will get confused by this syntax and think that things need to be formatted in special way rather than just a simple string.

That's the new SFI pattern and mandate. Any markup or code that is copy/pasted must throw an error to prevent copy paste. We can monitor the doc if ppl have problems and add some comments helping them.

2025-01-06 22:01 UTC, mthalman approved these changes

2025-01-06 22:28 UTC, lbussell commented on samples/run-aspnetcore-https-development.md
> +dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" "<`"CREDENTIAL" "PLACEHOLDER`>"
I was playing around with other formats. This one works (or rather, doesn't work):

```
> dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Default:Password" $CREDENTIAL_PLACEHOLDER

Missing parameter value for 'value'.
Use the '--help' flag to see info.
```

It also passes AzDO credential check. Since it looks so much better I'm going to update to that.

2025-01-06 22:38 UTC, mthalman approved these changes

2025-01-06 23:04 UTC, Rick-Anderson approved these changes

2025-01-07 16:18 UTC, merged